# Generated by Django 3.2.8 on 2021-10-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldData', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'form_data',
            },
        ),
    ]
