# Generated by Django 3.2.8 on 2021-10-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211015_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='ImageData',
            field=models.ImageField(default='null', upload_to='api'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formdata',
            name='NumberOfAnswerBox',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
