# Generated by Django 3.2.8 on 2021-10-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211015_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='ImageData',
            field=models.ImageField(upload_to='api/images'),
        ),
    ]
