# Generated by Django 3.2.8 on 2021-10-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_formdata_imagedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='AlternateDelimeter',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='AnswerCheckType',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='AnswerType',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='BoxDelimeter',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='Hint',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='NumberOfAnswerBox',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='RangeHigherLimit',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='RangeLowerLimit',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='SecondaryAnswer',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='SecondaryAnswerType',
        ),
        migrations.AddField(
            model_name='formdata',
            name='Clue',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='CorrectAnswer',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
