# Generated by Django 3.2.8 on 2021-10-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211023_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='ImageData',
            field=models.ImageField(upload_to='images'),
        ),
    ]
